# Generated by Django 2.1.5 on 2021-04-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
